---
language: python
python:
  - "3.8"
services:
  - mysql
  - redis-server
branches:
  only:
    - master
before_install:
  - mysql -e "CREATE DATABASE tickers;"
  - mysql -e "CREATE DATABASE tickers_test;"
  - mysql -e "CREATE USER tickers@localhost IDENTIFIED BY 'tickers';"
  - mysql -e "GRANT ALL ON tickers.* TO tickers@localhost IDENTIFIED BY 'tickers';"
  - mysql -e "GRANT ALL ON tickers_test.* TO tickers@localhost IDENTIFIED BY 'tickers';"
install:
  - pip install ansible==2.9.6
  - pip install -r requirements.txt
  - python manage.py db upgrade
stages:
  - name: tests
    if: type = pull_request
  - name: deploy
    if: branch in (master) AND type != pull_request
jobs:
  include:
    - stage: tests
      name: "Test given pull-request"
      script: |
        python manage.py test
    - stage: deploy
      name: "Deploy code to target servers"
      env: LIMIT=tickers
      before_script: |
        echo "Checkout ansible controller repository"
        eval "$(ssh-agent -s)"
        ssh-add <(echo "$MACHINE_GUNNER_PKEY")
        export GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
        git clone --depth=1 git@github.com:oomag/ansible_controller.git
        echo "Ensure roles needed for deploy"
        pushd ansible_controller
        ./tools/get-roles.sh tickers-roles.yml
        echo "Ensure SSH key to login to target hosts"
        export ANSIBLE_VAULT_PASSWORD_FILE=$(readlink -f ./tools/get-vault-pass)
        ansible-playbook --limit $LIMIT --tags local -e @vars/extra.yaml run-ci-prerequisites.yml
        for key in /tmp/.ssh/*; do
          ssh-add $key
        done
      script: |
        echo "Run deploy on $LIMIT nodes set"
        ansible-playbook --limit $LIMIT -e @vars/extra.yaml run-tickers.yml
