---
language: python
python:
  - "3.8"
services:
  - mysql
  - redis-server
branches:
  only:
    - master
before_install:
  - mysql -e "CREATE DATABASE tickers;"
  - mysql -e "CREATE DATABASE tickers_test;"
  - mysql -e "CREATE USER tickers@localhost IDENTIFIED BY 'tickers';"
  - mysql -e "GRANT ALL ON tickers.* TO tickers@localhost IDENTIFIED BY 'tickers';"
  - mysql -e "GRANT ALL ON tickers_test.* TO tickers@localhost IDENTIFIED BY 'tickers';"
install:
  - pip install -r requirements.txt
  - python manage.py db upgrade
stages:
  - name: tests
    if: type = pull_request
  - name: deploy
    if: branch in (master) AND type != pull_request
jobs:
  include:
    - stage: tests
      name: "Test given pull-request"
      script: |
        python manage.py test
    - stage: deploy
      name: "Deploy code to target servers"
      script: |
        echo "And no deploy here yet"
