"""empty message

Revision ID: 432302ed4d99
Revises: 
Create Date: 2017-12-19 16:34:15.444997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '432302ed4d99'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('markets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pairs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tickers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('pair_id', sa.Integer(), nullable=False),
    sa.Column('bid', sa.Float(precision=32), nullable=True),
    sa.Column('ask', sa.Float(precision=32), nullable=True),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['pair_id'], ['pairs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tickers')
    op.drop_table('pairs')
    op.drop_table('markets')
    # ### end Alembic commands ###
