"""empty message

Revision ID: f5745b4beee9
Revises: 432302ed4d99
Create Date: 2017-12-21 16:17:55.369499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5745b4beee9'
down_revision = '432302ed4d99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickers', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickers', 'created_at')
    # ### end Alembic commands ###
