"""is active pair

Revision ID: ff985fa1fa19
Revises: 959a2327f021
Create Date: 2021-03-06 15:13:26.950492

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ff985fa1fa19'
down_revision = '959a2327f021'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pairs', sa.Column('is_active', mysql.TINYINT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pairs', 'is_active')
    # ### end Alembic commands ###
